### ISSUE TITLE
sqlKeywords.txt missing

### ISSUE THREAD

**Issue by jewellsean** [alexandrebouchard/briefj#1]
I believe that the resource `sqlKeywords.txt` is missing. This causes errors with `briefj.db.Records.cleanColumnName`.

Since you likely have a keywords file, I will build and push a version to my own maven server, but wanted to record the missing file here. 

Thanks!

**Comment by jewellsean** [comment]
After some more digging, it seems that this may be due to the fact that the current (online portion) of this repo is out of date. Latest version here seems to be 2.3.8, but for example `westrun` pulls 2.4.2 from maven repo online. 

My best guess is that version 2.4.2 of the repo contains this resource, but the resource is not being built into the maven upload. This causes `westrun` to break, but I am posting here since this is the root of the problem.

**Comment by alexandrebouchard** [comment]
The above commit should hopefully fix this. I had the resource in the test directory instead of main, which causes the file not to be included in the production maven jars. I pushed a new 2.4.3 artifact, which is not yet referenced in westrun.
